### PR TITLE
feat: mmap transport for macos

### PR DESCRIPTION
**Pull request by usamoi**
Not tested.

### CODE REVIEW

**Comment by silver-ymz** [comment]
I test it on my macbook air (m1).
```
db error: ERROR: called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
```

**Comment by usamoi** [comment]
@silver-ymz Could you run sqllogictest tests on the latest commit?

**Comment by VoVAllen** [comment]
I don't think we need to check so many versions. It is best to control the CI duration within 5 minutes.

**Comment by usamoi** [comment]
@VoVAllen
All checks in linux can be finished in 10 minutes. However, checks in MacOS need about 20 minutes.

**Comment by VoVAllen** [comment]
Please move most tests to merge queue test according to https://stackoverflow.com/questions/62846375/perform-github-action-when-trying-to-merge-branch. One check is enough for each commit I think. Run all the tests only when the PR got into the merge queue

**Comment by VoVAllen** [comment]
Or control the test manually by issue label like
```
on:
  label:
    types: [run-full-ci]
```

**Comment by VoVAllen** [comment]
Does https://github.com/tensorchord/pgvecto.rs/pull/139 depend on this PR for postgres 14? cc @silver-ymz

**Comment by silver-ymz** [comment]
> Does https://github.com/tensorchord/pgvecto.rs/pull/139 depend on this PR for postgres 14?

No.

**Comment by usamoi** [comment]
@VoVAllen We need to modify branch protection rules.

**Comment by VoVAllen** [comment]
I'm on the train. Will modify it when go home

**Pull request merged**
