### PR TITLE
refactor: orthogonal support of vbase and prefilter

### LINKED ISSUE #188: feat(docs): VBASE documentation
Hi! I noticed you recently added support for VBASE. I'd like to learn a bit more about the use-case for this. I see that it's mutually exclusive with pre-filtering. Does it fulfill a similar purpose? When would I prefer one or the other?

And from skimming the VBASE paper, it seems that part of the algorithm uses a distance-based range filter. Is there a way to optimize range-based queries using this, i.e. for queries where we want to find all the vectors within a certain distance? 

The current approach we have is [here](https://github.com/immich-app/immich/blob/0aae9696f68b830d918780d9c3ffca74352adea9/server/src/infra/repositories/smart-info.repository.ts#L85), where we do pre-filtering on a number of conditions and then do post-filtering on the max distance. If we put the max distance condition in the pre-filtering stage, there's a big performance penalty. But if we apply it through post-filtering, we don't necessarily return all of the rows within that distance, just those within the top k. Would VBASE help with this?

And as always, thank you for working on this project! We made our first release with pgvecto.rs and the rollout has been relatively smooth. The issues relating to pgvecto.rs were mainly because some users used the `latest` docker tag instead of a proper release version.

### LINKED ISSUE #205: `enable_prefilter` doesn't seem to work correctly.
Hello, thank you for the amazing extension. I am working on Immich app and encounter this scenario, which I hope you can help me with some explanation.

Immich is a photo backup app with multiple users on the same instance. I am trying to search for the record belonging to a specific user. However, I see that the query would get the relevant results from other users as well before applying the "WHERE" clause conditions, with `enable_prefilter=on`

My expectation is to be able to get all the records of a user first, before searching for the closest match vector result.

Here is the SQL statement that we use.

```sql
START TRANSACTION;
SET LOCAL vectors.k = 100;
SET LOCAL vectors.enable_prefilter = on;
SELECT "a"."id"                 AS "a_id",
       "a"."deviceAssetId"      AS "a_deviceAssetId",
       "a"."ownerId"            AS "a_ownerId",
       "a"."libraryId"          AS "a_libraryId",
       "a"."deviceId"           AS "a_deviceId",
       "a"."type"               AS "a_type",
       "a"."originalPath"       AS "a_originalPath",
       "a"."resizePath"         AS "a_resizePath",
       "a"."webpPath"           AS "a_webpPath",
       "a"."thumbhash"          AS "a_thumbhash",
       "a"."encodedVideoPath"   AS "a_encodedVideoPath",
       "a"."createdAt"          AS "a_createdAt",
       "a"."updatedAt"          AS "a_updatedAt",
       "a"."deletedAt"          AS "a_deletedAt",
       "a"."fileCreatedAt"      AS "a_fileCreatedAt",
       "a"."localDateTime"      AS "a_localDateTime",
       "a"."fileModifiedAt"     AS "a_fileModifiedAt",
       "a"."isFavorite"         AS "a_isFavorite",
       "a"."isArchived"         AS "a_isArchived",
       "a"."isExternal"         AS "a_isExternal",
       "a"."isReadOnly"         AS "a_isReadOnly",
       "a"."isOffline"          AS "a_isOffline",
       "a"."checksum"           AS "a_checksum",
       "a"."duration"           AS "a_duration",
       "a"."isVisible"          AS "a_isVisible",
       "a"."livePhotoVideoId"   AS "a_livePhotoVideoId",
       "a"."originalFileName"   AS "a_originalFileName",
       "a"."sidecarPath"        AS "a_sidecarPath",
       "a"."stackParentId"      AS "a_stackParentId",
       "e"."assetId"            AS "e_assetId",
       "e"."description"        AS "e_description",
       "e"."exifImageWidth"     AS "e_exifImageWidth",
       "e"."exifImageHeight"    AS "e_exifImageHeight",
       "e"."fileSizeInByte"     AS "e_fileSizeInByte",
       "e"."orientation"        AS "e_orientation",
       "e"."dateTimeOriginal"   AS "e_dateTimeOriginal",
       "e"."modifyDate"         AS "e_modifyDate",
       "e"."timeZone"           AS "e_timeZone",
       "e"."latitude"           AS "e_latitude",
       "e"."longitude"          AS "e_longitude",
       "e"."projectionType"     AS "e_projectionType",
       "e"."city"               AS "e_city",
       "e"."livePhotoCID"       AS "e_livePhotoCID",
       "e"."state"              AS "e_state",
       "e"."country"            AS "e_country",
       "e"."make"               AS "e_make",
       "e"."model"              AS "e_model",
       "e"."lensModel"          AS "e_lensModel",
       "e"."fNumber"            AS "e_fNumber",
       "e"."focalLength"        AS "e_focalLength",
       "e"."iso"                AS "e_iso",
       "e"."exposureTime"       AS "e_exposureTime",
       "e"."profileDescription" AS "e_profileDescription",
       "e"."colorspace"         AS "e_colorspace",
       "e"."bitsPerSample"      AS "e_bitsPerSample",
       "e"."fps"                AS "e_fps"
FROM "assets" "a"
         INNER JOIN "smart_search" "s" ON "s"."assetId" = "a"."id"
         LEFT JOIN "exif" "e" ON "e"."assetId" = "a"."id"
WHERE (
            "a"."ownerId" = '7f9087b2-3f6e-4b08-9b8f-f16999c3c89d'
        AND "a"."isVisible" = true
        AND "a"."isArchived" = false
        AND "a"."fileCreatedAt" < NOW()
    )
  AND ("a"."deletedAt" IS NULL)
ORDER BY "s"."embedding" <=> '[-0.014400768,0.013051721,-0.047649417,...]' ASC
LIMIT 100;
COMMIT;
```

Please let me know if we are doing something wrong here

I appreciate your time

Thanks,
Alex

### PR DESCRIPTION
**Pull request by usamoi**
* PR in pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/248
* PR in pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/7
* closes #188
* closes #205
* ref #250

change:
* both `basic` and `vbase` use a iterator-like interface now
  * `vectors.k` is confusing for users, so it's removed
  * fixes the bug that a transction aborts if there is two running vector index query in the same time. we may need multiplexing in IPC
* introduce search mode:
  * rename many `search` in code to `basic`, to keep consistency with the document
* the semantics of `filter`
  * it should be called at least once on the returned pointer and `check` must return true for them
  * it's a cheap check, so checking it before computing distance is acceptable or recommended
  * `prefilter` will be implemented like this:
    * introduce rocksdb or something else to support save payload in index (multicolumn index)
    * generate a checking expression from where clause, which can be false postive
    * pass the checker function (checking expression) to `basic` and `vbase`

### CODE REVIEW

**Comment by VoVAllen** [comment]
please describe the interface change in the pr

**Comment by usamoi** [comment]
what is interface change?

**Comment by VoVAllen** [comment]
Such as introduce new options `vectors.search_mode` etc. / why remove `vectors.k`

**Comment by usamoi** [comment]
PTAL @VoVAllen

**Review by VoVAllen — APPROVED** [review]
> it's a cheap check, so checking it before computing distance is acceptable or recommended

I'm a bit skeptical because this may involve disk IO.

> prefilter will be implemented like this:
introduce rocksdb or something else to support save payload in index (multicolumn index)
generate a checking expression from where clause, which can be false postive
pass the checker function (checking expression) to basic and vbase

I think this needs more discussion. I didn't see why it helps the performance. Multicolumn index I think is used to build categorical hnsw, and not related to the search part.

**Review by VoVAllen — APPROVED** [review]
Overall LGTM

**Comment by usamoi** [comment]
> I'm a bit skeptical because this may involve disk IO.

It's cheaper compared to comunicating with PostgreSQL.

> I think this needs more discussion. I didn't see why it helps the performance. Multicolumn index I think is used to build categorical hnsw, and not related to the search part.

It scans less points so it performs better. It's related to the search part because we need to save the payload and access them in the background process.

**Comment by VoVAllen** [comment]
> > I'm a bit skeptical because this may involve disk IO.
> 
> It's cheaper compared to comunicating with PostgreSQL.
> 
> > I think this needs more discussion. I didn't see why it helps the performance. Multicolumn index I think is used to build categorical hnsw, and not related to the search part.
> 
> It scans less points so it performs better. It's related to the search part because we need to save the payload and access them in the background process.

Disk IO is more expensive than communicating with PG I think.
And what's the payload you're referring to here?

**Comment by usamoi** [comment]
> Disk IO is more expensive than communicating with PG I think.

communicating with PG is more expensive than Disk IO I think. Even if all buffer are in memory, it's really slow in our previous tests.

> And what's the payload you're referring to here?

"payload" is the data outside vector columns. for example, in a table `id, name, vector`, `id, name` can be payload.

**Comment by VoVAllen** [comment]
> > Disk IO is more expensive than communicating with PG I think.
> 
> communicating with PG is more expensive than Disk IO I think. Even if all buffer are in memory, it's really slow in our previous tests.
> 
> > And what's the payload you're referring to here?
> 
> "payload" is the data outside vector columns. for example, in a table `id, name, vector`, `id, name` can be payload.

Why we need `name, vector` in our payload? id should be enough? I didn't see any advantage that we make the check at our side comparing to at pg side

**Comment by usamoi** [comment]
> Why we need name, vector in our payload? id should be enough? I didn't see any advantage that we make the check at our side comparing to at pg side

check at pg side is **very slow**, even at least doube time compared to search. if we check at pg side and it performs slower because of prefiltering, why we need prefilter?

**Comment by usamoi** [comment]
Let's say we use flat or ivf and the selective is 1%. If we performs a cheap check before computing the distance, the time consuming in "computing the distance" is 1% compared to before.

**Comment by usamoi** [comment]
For HNSW, it's even more smaller because the graph is smaller. the time consuming in "computing the distance" is 0.1% compared to before.

**Comment by VoVAllen** [comment]
I feel it's impossible to keep the HNSW graph connectivity even with 1% selectivity rate, which means you need at least 100 edges for each nodes. For ivf, I'm not sure. Need more studies

**Comment by usamoi** [comment]
> I feel it's impossible to keep the HNSW graph connectivity even with 1% selectivity rate

I think it's why we need categorical HNSW.

> For ivf, I'm not sure.

What applies to FLAT also applies to IVF. IVF is just a brute force algorithm in optimized search list.

**Comment by VoVAllen** [comment]
@usamoi Let's say I have 100 category. How can I build the categorical hnsw graph to avoid disconnectivity with limited edges?  I feel like still 100 edges on average is needed

**Comment by VoVAllen** [comment]
But why the centroid in ivf can represent the filter condition of the whole cluster? It needs some assumptions between the filter condition and search process I think

**Comment by usamoi** [comment]
> But why the centroid in ivf can represent the filter condition of the whole cluster?

We do not skip scanning the cluster if the centroid is failed to pass the check.

**Comment by usamoi** [comment]
> Let's say I have 100 category. How can I build the categorical hnsw graph to avoid disconnectivity with limited edges? I feel like still 100 edges on average is needed

We build HNSW graph for every category and and merge 101 graphs.

**Pull request merged**
