### PR TITLE
feat: Puck

### PR DESCRIPTION
**Pull request by whateveraname**
Implemented the [Puck](https://github.com/baidu/puck) algorithm, which essentially consists of a two-layer IVF index and a two-layer product quantization.

### CODE REVIEW

**Comment by gaocegege** [comment]
Hi is it ready to review?

**Comment by VoVAllen** [comment]
@gaocegege The author told me our product quantization has some precision issues. He's working on it now

**Comment by usamoi** [comment]
Please resolve conflicts.

**Comment by whateveraname** [comment]
I'm currently not working on this PR, will close it soon.

**Pull request closed without merging**
