### PR TITLE
chore: update the extention description

### PR DESCRIPTION
**Pull request by kemingy**

### CODE REVIEW

**Comment by usamoi** [comment]
This PR is breaking. We must use `tensorchord.vector(1000)` instead of `vector(1000)` and `USING tensorchord.vectors` instead of `USING vectors`.

**Comment by kemingy** [comment]
> This PR is breaking. We must use `tensorchord.vector(1000)` instead of `vector(1000)` and `USING tensorchord.vectors` instead of `USING vectors`. Operators do not work now.

I think it's better to have a separate schema instead of the `public` one since there are multiple extensions called "vector".

As for the breaking, we only need to update the doc.

**Comment by usamoi** [comment]
Not everything can be put into a separate schema. Schema-qualified operators are hard to use.[^0]

[^0]: https://dba.stackexchange.com/questions/191695/is-it-possible-to-schema-qualify-an-operator

**Comment by VoVAllen** [comment]
Use a seperate PR for dco https://github.com/tensorchord/pgvecto.rs/pull/121

**Comment by usamoi** [comment]
If users need, they can use `CREATE EXTESNION vectors WITH SCHEMA tensorchord`.

**Comment by kemingy** [comment]
This is how paradedb does:
- https://github.com/paradedb/paradedb/blob/2b3919a20edd5bc40724e26a56b84538e70d66ec/scripts/entrypoint.sh#L75

**Pull request merged**
