### PR TITLE
feat: add Python bindings

### PR DESCRIPTION
**Pull request by AuruTus**
Add python bindings for pgvector.rs to better integrate with langchain and llamaindex.

related issue #58 

# Major Changes

- [x] add python binding for sqlalchemy

### CODE REVIEW

**Comment by BeautyyuYanli** [comment]
Hello https://github.com/AuruTus, is there any update on this PR?

**Comment by kemingy** [comment]
Close this one since the code has been merged in #95

**Comment by VoVAllen** [comment]
https://github.com/all-contributors please add @AuruTus for code contribution

**Comment by VoVAllen** [comment]
@all-contributors please add @AuruTus for code contribution

**Pull request closed without merging**
