### PR TITLE
feat: support vector subscript

### PR DESCRIPTION
**Pull request by usamoi**
Address #327

Now we support such a syntax:

```sql
CREATE TABLE t(val vector(3));
INSERT INTO t (val) SELECT ARRAY[random(), random(), random()]::real[] FROM generate_series(1, 100000);
CREATE INDEX t_vector_index on t using vectors((val[:1]::vector(1)) vector_l2_ops);
SELECT * FROM t ORDER BY val[:1]::vector(1) <-> '[0]' limit 10;
```

It's only supported by pg14, pg15 and pg16.

### CODE REVIEW

**Comment by VoVAllen** [comment]
The syntax using real[] is not consistent with other usage with vectors. Is it necessary?

**Comment by usamoi** [comment]
> The syntax using real[] is not consistent with other usage with vectors.

It's nothing about `real[]`.

> Is `vectors` a new function?

It's `vectors` AM handler. You can get reference of syntax in https://www.postgresql.org/docs/current/sql-createindex.html.

**Comment by VoVAllen** [comment]
Can I do `CREATE INDEX t_vector_index on t using vectors((val[16:32]::vector(16)) vector_l2_ops);` ?

**Comment by usamoi** [comment]
> Can I do `CREATE INDEX t_vector_index on t using vectors((val[16:32]::vector(16)) vector_l2_ops);` ?

Yes.

**Review by VoVAllen — DISMISSED** [review]

**Pull request merged**
