### PR TITLE
feat: implement square_euclidean_distance for f32, f64 and i32

### PR DESCRIPTION
**Pull request by skyzh**
This PR adds `square_euclidean_distance` for different types and more test cases. PTAL thanks!

### CODE REVIEW

**Comment by skyzh** [comment]
cc @kemingy @gaocegege

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Review by kemingy — APPROVED** [review]

**Comment by kemingy** [comment]
CI failed due to the version conflict. I'll fix it later. Thanks for your contribution!

**Comment by gaocegege** [comment]
@all-contributors Please add skyzh for the code contribution.

**Pull request merged**
