### PR TITLE
fix: reindex failed due to existing old index

### LINKED ISSUE #154: bug: Reindexing failed due to the existence of old index directory
reproduce:
```sql
CREATE TABLE t (val vector(3));
INSERT INTO t (val) SELECT ARRAY[random(), random(), random()]::real[] FROM generate_series(1, 1000);
CREATE INDEX ON t USING vectors (val l2_ops) WITH (options = "[indexing.hnsw]");
REINDEX INDEX t_val_idx;
```

psql output:
```
ERROR:  called `Result::unwrap()` on an `Err` value: Closed
```

pgvecto.rs log:
```
[2023-11-21T01:42:02Z ERROR vectors::bgworker] Panickied. Info: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }), location: Location { file: "src/index/mod.rs", line: 79, col: 36 }, can_unwind: true, force_no_backtrace: false }. Backtrace:    0: vectors::bgworker::main::{{closure}}
                 at /home/ymz/code/project/pgvecto.rs/src/bgworker/mod.rs:37:25
       1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/alloc/src/boxed.rs:2021:9
       2: std::panicking::rust_panic_with_hook
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:783:13
       3: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:657:13
       4: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:170:18
       5: rust_begin_unwind
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:645:5
       6: core::panicking::panic_fmt
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/panicking.rs:72:14
       7: core::result::unwrap_failed
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/result.rs:1649:5
       8: core::result::Result<T,E>::unwrap
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/result.rs:1073:23
       9: vectors::index::Index::create
                 at /home/ymz/code/project/pgvecto.rs/src/index/mod.rs:79:9
      10: vectors::bgworker::worker::Worker::call_create
                 at /home/ymz/code/project/pgvecto.rs/src/bgworker/worker.rs:63:21
      11: vectors::bgworker::thread_session
                 at /home/ymz/code/project/pgvecto.rs/src/bgworker/mod.rs:96:17
      12: vectors::bgworker::thread_main_2::{{closure}}
                 at /home/ymz/code/project/pgvecto.rs/src/bgworker/mod.rs:83:33
      13: std::sys_common::backtrace::__rust_begin_short_backtrace
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys_common/backtrace.rs:154:18
      14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/thread/mod.rs:529:17
      15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/panic/unwind_safe.rs:272:9
      16: std::panicking::try::do_call
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:552:40
      17: __rust_try
      18: std::panicking::try
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panicking.rs:516:19
      19: std::panic::catch_unwind
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/panic.rs:142:14
      20: std::thread::Builder::spawn_unchecked_::{{closure}}
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/thread/mod.rs:528:30
      21: core::ops::function::FnOnce::call_once{{vtable.shim}}
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/core/src/ops/function.rs:250:5
      22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/alloc/src/boxed.rs:2007:9
      23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/alloc/src/boxed.rs:2007:9
      24: std::sys::unix::thread::Thread::new::thread_start
                 at /rustc/dd430bc8c22f57992ec1457a87437d14283fdd65/library/std/src/sys/unix/thread.rs:108:17
      25: start_thread
                 at ./nptl/pthread_create.c:442:8
      26: __GI___clone3
                 at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### PR DESCRIPTION
**Pull request by silver-ymz**
close #154

fix:
- Reindexing fails due to existing old index
- Droping index may not to remove dir because optimizing thread holds index arc when parking

### CODE REVIEW

**Comment by usamoi** [comment]
alloate different path for any (recreated) indexes, we should keep logic in index is simple

**Comment by usamoi** [comment]
we can allocate uuid for index and map oid to uuid in worker

**Comment by silver-ymz** [comment]
I replace the id passed by rpc from index id to its storage id. Now we don't need to handle additional logic for reindexing.

**Comment by silver-ymz** [comment]
@usamoi It's ready to review.

**Review by usamoi — APPROVED** [review]

**Pull request merged**
