### PR TITLE
fix: cosine distance

### PR DESCRIPTION
**Pull request by kemingy**
- refer to https://github.com/tensorchord/pgvecto.rs/issues/227

### CODE REVIEW

**Review by gaocegege — DISMISSED** [review]

**Comment by VoVAllen** [comment]
How about PQ and SQ distance?

**Comment by kemingy** [comment]
> How about PQ and SQ distance?

Fixed in the new commit. PTAL

**Review by usamoi — COMMENTED** [review]
I suggest add a postgres_distance function to the `G` trait and use it for displaying.

**Comment by kemingy** [comment]
> Can we just use `1.0-cos` and `sqrt(squared l2)` for PostgreSQL operator?

I don't have the plan to replace the squared L2 distance.

**Comment by gaocegege** [comment]
Please resolve the conflicts.

> Can we just use `1.0-cos` and `sqrt(squared l2)` for PostgreSQL operator?

It will add more overhead to the compute, but we do not see the benefits. Thus let's keep no sqrt for now.

**Comment by kemingy** [comment]
> Please resolve the conflicts.

fixed

**Comment by gaocegege** [comment]
PTAL @usamoi @VoVAllen

**Review by usamoi — COMMENTED** [review]
Please fix:
`https://github.com/tensorchord/pgvecto.rs/blob/a7a9a592c1ef8db0c41ff106b62c85359c10a3b1/README.md?plain=1#L109`
`https://github.com/tensorchord/pgvecto.rs/blob/a7a9a592c1ef8db0c41ff106b62c85359c10a3b1/README.md?plain=1#L118`
`https://github.com/tensorchord/pgvecto.rs/blob/a7a9a592c1ef8db0c41ff106b62c85359c10a3b1/crates/service/src/instance/metadata.rs#L21`

**Comment by VoVAllen** [comment]
I think we can also add sqrt in L2 to make in consistent at all. The impact on performance should be negligible.

**Comment by VoVAllen** [comment]
> Can we just use `1.0-cos` and `sqrt(squared l2)` for PostgreSQL operator?

I think this is the better way. We can add sqrt to PostgresSQL operator. If user didn't use L2 instance in the query, no extra cost will be introduced? And we can make it consistent with pgvector at all

**Comment by usamoi** [comment]
> @usamoi Will the cost of sqrt happen when user doesn't need distance in the query?

No, there will be no extra cost. What I cares is consistency: we use `l2` for opeator name but it's `l2s`(`l2-squared`) in fact.

**Comment by kemingy** [comment]
Cosine distance has to be fixed because it's defined as `1 - cosine_similarity`. For the L2 distance, if you choose to impl squared L2, it's also widely accepted. I don't think it's necessary to get the square root.

**Comment by usamoi** [comment]
We didn't implement `Cosine distance`. What we implemented before is `negative cosine similarity` and we take `cos` for short. It's consistency with users who chooses to normalize the vector and use `negative dot product`.

**Review by usamoi — APPROVED** [review]

**Review by VoVAllen — APPROVED** [review]

**Pull request merged**
